import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { Keypair } from '@veil-cash/sdk';
import { VEIL_ENV_PATH, getDepositKey, getVeilKey } from './env.js';

function updateEnvVar(content: string, key: string, value: string): string {
  const regex = new RegExp(`^${key}=.*`, 'm');
  if (regex.test(content)) {
    return content.replace(regex, `${key}=${value}`);
  }
  const prefix = content && !content.endsWith('\n') ? `${content}\n` : content;
  return `${prefix}${key}=${value}\n`;
}

function saveVeilKeypair(veilKey: string, depositKey: string, envPath = VEIL_ENV_PATH): void {
  const dir = dirname(envPath);
  if (dir && dir !== '.' && !existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const initial = '# Veil Cash Configuration\n# Generated by: veil-mcp\n\n';
  let content = existsSync(envPath) ? readFileSync(envPath, 'utf8') : initial;
  content = updateEnvVar(content, 'VEIL_KEY', veilKey);
  content = updateEnvVar(content, 'DEPOSIT_KEY', depositKey);
  writeFileSync(envPath, content, { mode: 0o600 });
}

export function getKeyStatus(): {
  veilKeyFound: boolean;
  depositKeyFound: boolean;
  depositKey?: `0x${string}`;
  maskedDepositKey?: string;
} {
  const veilKey = getVeilKey();
  const envDepositKey = getDepositKey();
  const derivedDepositKey = veilKey ? (new Keypair(veilKey).depositKey() as `0x${string}`) : undefined;
  const depositKey = envDepositKey || derivedDepositKey;

  return {
    veilKeyFound: Boolean(veilKey),
    depositKeyFound: Boolean(depositKey),
    depositKey,
    maskedDepositKey: depositKey ? maskHex(depositKey) : undefined,
  };
}

export function requireKeypair(): Keypair {
  const veilKey = getVeilKey();
  if (!veilKey) {
    throw new Error('VEIL_KEY missing. Call veil_init_keypair first or provide VEIL_KEY in .env.veil.');
  }
  return new Keypair(veilKey);
}

export function requireDepositKey(): `0x${string}` {
  const status = getKeyStatus();
  if (!status.depositKey) {
    throw new Error('DEPOSIT_KEY missing. Call veil_init_keypair first or provide DEPOSIT_KEY in .env.veil.');
  }
  return status.depositKey;
}

export function initRandomKeypair(options: { force?: boolean } = {}): {
  success: true;
  savedTo: string;
  derivation: 'random';
  depositKey: `0x${string}`;
} {
  const existing = getKeyStatus();
  if (existing.veilKeyFound && !options.force) {
    throw new Error('A Veil key already exists. Pass force: true to overwrite .env.veil.');
  }

  const keypair = new Keypair();
  const veilKey = keypair.privkey;
  if (!veilKey) {
    throw new Error('Failed to generate Veil keypair.');
  }

  const depositKey = keypair.depositKey() as `0x${string}`;
  saveVeilKeypair(veilKey, depositKey);
  process.env.VEIL_KEY = veilKey;
  process.env.DEPOSIT_KEY = depositKey;

  return {
    success: true,
    savedTo: VEIL_ENV_PATH,
    derivation: 'random',
    depositKey,
  };
}

export function maskHex(value: string): string {
  if (value.length <= 18) return value;
  return `${value.slice(0, 10)}...${value.slice(-8)}`;
}

